name: test and release

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run prettier
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test:coverage -- --reporter=junit

  release:
    needs: test
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.release.outputs.version }}
      new_release_published: ${{ steps.release.outputs.new_release_published }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --save-dev semantic-release@23 @semantic-release/changelog@6 @semantic-release/git@10 @semantic-release/exec@6 conventional-changelog-conventionalcommits@7

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@23.0.7
